///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class R {
  R._();

  static const String imagesIconHomeGrey = 'assets/images/icon_home_grey.png';
  static const String imagesIconHomeSelected = 'assets/images/icon_home_selected.png';
  static const String imagesIconHotKeyGrey = 'assets/images/icon_hot_key_grey.png';
  static const String imagesIconHotKeySelected = 'assets/images/icon_hot_key_selected.png';
  static const String imagesIconKnowledgeGrey = 'assets/images/icon_knowledge_grey.png';
  static const String imagesIconKnowledgeSelected = 'assets/images/icon_knowledge_selected.png';
  static const String imagesIconMessageGrey = 'assets/images/icon_message_grey.png';
  static const String imagesIconMessageSelected = 'assets/images/icon_message_selected.png';
  static const String imagesIconPersonalGrey = 'assets/images/icon_personal_grey.png';
  static const String imagesIconPersonalSelected = 'assets/images/icon_personal_selected.png';
  static const String imagesIconSearch = 'assets/images/icon_search.png';
  static const String imagesImgCollect = 'assets/images/img_collect.png';
  static const String imagesImgCollectGrey = 'assets/images/img_collect_grey.png';
  static const String imagesLogo = 'assets/images/logo.png';

}
